### ISSUE TITLE
Tracking Top/Bottom Dropdown State Separately

### ISSUE THREAD

**Issue by jakejackson1** [GravityPDF/gravity-pdf-bulk-generator#17]
https://github.com/GravityPDF/gravity-pdf-bulk-generator/blob/development/src/assets/react/BulkGenerator.js#L105-L140

Do we actually need to track the top and bottom dropdown state separately? Couldn't see have a single "selected" option that we enable/disabled, which we then use to toggle the model https://github.com/GravityPDF/gravity-pdf-bulk-generator/blob/development/src/assets/react/BulkGenerator.js#L155-L156?

**Comment by debbieellis7** [comment]
We need to keep track on the top and bottom 'selectbox' separately since their ID's are also different @jakejackson1 . Also I think that's a more simpler approach considering that there are more available values in the 'selectbox' to choose from.
![3](https://user-images.githubusercontent.com/10412650/74212764-cc235e80-4cd0-11ea-841a-8ef7e963b2a7.png)

**Comment by debbieellis7** [comment]
And also when 'Download PDF' is selected from the top it needs to work only for the top apply button, same goes to the bottom box.
